name: Deploy Next.js

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Project Front End BBPOM di Mataram
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 56710
          script: |
            set -e

            echo "[Deploy] Fetch latest code..."
            cd /home/bbpommataram.id/PERCEPAT || exit
            git fetch --all
            git reset --hard origin/main

            echo "[Deploy] Load NVM..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22

            npm ci
            echo "[Deploy] Build Next.js..."
            NODE_OPTIONS="--max-old-space-size=4096" npm run build -- --no-lint
            pm2 restart percepat

            echo "[Deploy] Done ✅"
