name: Deploy Next.js

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Detect perubahan dependency
      - name: Check dependency changes
        id: deps
        uses: dorny/paths-filter@v3
        with:
          filters: |
            deps:
              - 'package.json'
              - 'package-lock.json'

      # 3️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      # 4️⃣ Install dependencies (WAJIB di runner)
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Build Next.js
      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_BACKEND_URL_PERCEPAT: ${{ secrets.NEXT_PUBLIC_BACKEND_URL_PERCEPAT }}
          NEXT_PUBLIC_BACKEND_URL_AUTH: ${{ secrets.NEXT_PUBLIC_BACKEND_URL_AUTH }}
          NEXT_PUBLIC_BACKEND_URL_SIAP_MELAYANI: ${{ secrets.NEXT_PUBLIC_BACKEND_URL_SIAP_MELAYANI }}
          NEXT_PUBLIC_BACKEND_URL_SIMPEL_BMN: ${{ secrets.NEXT_PUBLIC_BACKEND_URL_SIMPEL_BMN }}
          NEXT_PUBLIC_BACKEND_URL_BEST_EMPLOYEE: ${{ secrets.NEXT_PUBLIC_BACKEND_URL_BEST_EMPLOYEE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}

      # 6️⃣ Upload build ke VPS
      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 56710
          source: ".next,public,package.json,package-lock.json,ecosystem.config.js"
          target: "/home/bbpommataram.id/PERCEPAT"

      # 7️⃣ Install dependency jika berubah + restart PM2
      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 56710
          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22

            cd /home/bbpommataram.id/PERCEPAT

            if [ "${{ steps.deps.outputs.deps }}" = "true" ]; then
              echo "Dependencies changed → install"
              npm ci --omit=dev
            else
              echo "Dependencies unchanged → skip install"
            fi

            pm2 startOrRestart ecosystem.config.js
