name: Deploy Next.js

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Jalankan deploy langsung di server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 56710
          script: |
            echo "[Deploy] Fetch latest code..."
            cd /home/bbpommataram.id/PERCEPAT || exit
            git fetch --all
            git reset --hard origin/main

            echo "[Deploy] Install dependencies..."
            npm install --omit=dev

            echo "[Deploy] Build Next.js..."
            npm run build

            echo "[Deploy] Restart app..."
            pm2 restart 0

            echo "[Deploy] Done ✅"
