name: Deploy BBPOM Mataram

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 56710
          script: |
            cd /tmp/percepat-fe
            git pull origin main
            npm ci
            NODE_OPTIONS="--max-old-space-size=8192" npx next build
            cp -r .next /home/bbpommataram.id/PERCEPAT/.next
            chown -R cyberpanel:cyberpanel /home/bbpommataram.id/PERCEPAT/.next
            cd /home/bbpommataram.id/PERCEPAT
            pm2 restart percepat
